on: 
 push:
   branches:
     -master
name: Deploy PHP
jobs:
  web-deploy: 
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Code
      uses: action/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
